[package]
name = "wubilex-app"
version.workspace = true
edition.workspace = true
publish = false

[lib]
name = "wubilex_app"

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
specta = { version = "=2.0.0-rc.25", features = ["function"] }
specta-typescript = "=0.0.12"
tauri = { version = "=2.11.5", default-features = false, features = ["test"] }
tauri-specta = { version = "=2.0.0-rc.25", default-features = false, features = ["typescript"] }
