[package]
name = "wubilex-winime"
version.workspace = true
edition.workspace = true
publish = false

[target.'cfg(windows)'.dependencies]
windows = { version = "0.61.3", features = [
    "Win32_Security_Authorization",
    "Win32_System_Com",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Ole",
    "Win32_System_TaskScheduler",
    "Win32_System_Threading",
    "Win32_System_Variant",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_TextServices",
] }
