//! Canonical Tauri command and event registry used by runtime setup and binding export.

use std::path::Path;

use specta_typescript::Typescript;
use tauri::{Runtime, test::MockRuntime};
use tauri_specta::{Builder, collect_commands, collect_events};

/// Header included in every committed TypeScript binding artifact.
pub const GENERATED_HEADER: &str =
    "// This file is generated by `cargo xtask bindings`. Do not edit manually.";

/// Builds the single Rust-owned IPC registry for the selected Tauri runtime.
pub fn builder<R: Runtime>() -> Builder<R> {
    Builder::<R>::new()
        .commands(collect_commands![
            crate::commands::app::app_runtime_snapshot,
        ])
        .events(collect_events![crate::events::LaunchRequestedEvent])
}

/// Exports the canonical registry without constructing a Wry runtime.
pub fn export_mock(path: impl AsRef<Path>) -> Result<(), specta_typescript::Error> {
    builder::<MockRuntime>().export(Typescript::default().header(GENERATED_HEADER), path)
}
